/*Generated by SharpKit 5 v5.00.0000*/
if (typeof(randori) == "undefined")
    var randori = {};
randori.Class1 = function ()
{
};
randori.Class1.className = "randori.Class1";
randori.Class1.injectionPoints = function (t)
{
    var p;
    switch (t)
    {
        case 0:
            p =  [];
            return p;
        default :
            p =  [];
            break;
    }
    return p;
};
